config/routes.rb
Rails.application.routes.draw do
  resources :todos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "todos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]

  # GET /todos or /todos.json
  def index
    @todos = Todo.all
    @todo = Todo.new
  end

  # GET /todos/1 or /todos/1.json
  def show
  end

  # GET /todos/new
  def new
   
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.turbo_stream
        format.html { redirect_to todos_url, notice: "Todo was successfully created." }
      else
        # format.html { render :new, status: :unprocessable_entity }
        format.turbo_stream { render turbo_stream: turbo_stream.replace("#{helpers.dom_id(@todo)}_form", partial: "form", locals: { todo: @todo })}
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace("#{helpers.dom_id(@todo)}") }
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy
    puts 'In the process of being deleted'
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove("#{helpers.dom_id(@todo)}_item") }
      format.html { redirect_to todos_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:title, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TurboTodos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container mx-auto">
      <%= yield %>
    </div>
  </body>
</html>

app/views/todos/_errors.html.erb
<% if @todo.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h4>
      <a href="#" class="close" data-dismiss="alert">&#215;</a>
      <ul>
        <% @todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/todos/_form.html.erb
<div class="row">
  <div class="col">
    <%= form_with(model: todo, id: "#{dom_id(todo)}_form") do |form| %>
      <%= render "todos/errors" %>

      <div class="form-group d-flex">
      <div>
        <%#= form.label :title, style: "display: block" %>
        <%= form.text_field :title, class: "form-control", placeholder: "Add Todo" %>
      </div>

      <div>
        <%#= form.label :status, style: "display: block" %>
        <%#= form.number_field :status %>
      </div>

      
        <%= form.submit class: "btn btn-success" %>
      
      </div>
    <% end %>
  </div>
</div>

app/views/todos/_todo.html.erb
<div id="<%= "#{dom_id(todo)}_item" %>">
  <p>
    <!-- <strong>Title:</strong> -->
    <div class="card card-body">
      <div class="d-flex flex-row">
        <%= turbo_frame_tag dom_id(todo) do %>
          <span class="p-1"><strong><%= todo.title %></strong></span>
          <span class="p-1"><%= link_to "Edit", edit_todo_path(todo), class: "btn btn-warning btn-sm" %></span>
          <span class="button-inline"><%= button_to "Delete", todo_path(todo), method: :delete, class: "btn btn-danger btn-sm" %></span> 
        <% end %>
      </div>
    </div> 
  </p>
</div>

app/views/todos/create.turbo_stream.erb
<%= turbo_stream.prepend "todos" do %>
  <%= render "todo", todo: @todo %>
<% end %>

<%= turbo_stream.replace "#{dom_id(Todo.new)}_form" do %>
  <%= render "form", todo: Todo.new %>
<% end %>

app/views/todos/edit.html.erb
<%= turbo_frame_tag dom_id(@todo) do %>
  <%= render "form", todo: @todo %>
<% end %>



<br>

<div>
  <%= link_to "Show this todo", @todo %> |
  <%= link_to "Back to todos", todos_path %>
</div>

app/views/todos/index.html.erb
<div class="row">
  <p style="color: green"><%#= notice %></p>
  <div class="mx-auto">
    <h1>Todos</h1>
    <%= render 'form', todo: Todo.new %>
    <div id="todos">
      <%= render @todos %>
    </div>
  </div>
</div>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render "form", todo: @todo %>

<br>

<div>
  <%= link_to "Back to todos", todos_path %>
</div>

app/views/todos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @todo %>

<div>
  <%= link_to "Edit this todo", edit_todo_path(@todo) %> |
  <%= link_to "Back to todos", todos_path %>

  <%= button_to "Destroy this todo", @todo, method: :delete %>
</div>